services:
  # db:
  #   image: postgres:17.2
  #   environment:
  #     - POSTGRES_PASSWORD=${DB_PASSWORD}
  #     - POSTGRES_USER=${DB_USER}
  #     - POSTGRES_DB=${DB_NAME}
  #   ports:
  #     - ${DB_PORT}:5432
  #   volumes:
  #     - ./docker-data/db:/var/lib/postgresql/data
  mailhog:
    image: mailhog/mailhog:latest
    restart: always
    ports:
      - ${EMAIL_SERVER_PORT}:1025 # SMTP Port
      - ${EMAIL_SERVER_HTTP_PORT}:8025 # HTTP Port (Mailhog dashboard)
